name: Master

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.2'
      - run: pip install aws-sam-cli
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - uses: actions/checkout@v2
      - run: npm i
        working-directory: process-github-webhook
      - run: npm run build
        working-directory: process-github-webhook
      - run: npm prune --production
        working-directory: process-github-webhook
      - run: |
          sam deploy \
            --s3-bucket $APPLICATION_NAME-code-bucket \
            --stack-name $APPLICATION_NAME \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              AccountId=$ACCOUNT_ID \
              ApplicationName=$APPLICATION_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
